[package]
name = "valheim-log-parser"
version = "0.1.0"
authors = ["Nick Pelone <nick.pelone@calyptix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.4"
lazy_static = "1.4.0"
chrono = "0.4"
